name: allen_v1dd
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - comm=0.1.2
  - debugpy=1.6.6
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - jedi=0.18.2
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=3.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.14.0
  - python=3.10
  - python-dateutil=2.8.2
  - python_abi=3.10=2_cp310
  - pyzmq=25.0.0
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  # - sqlite=3.40.1
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wcwidth=0.2.6
  - wheel=0.38.4
  # - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.14.0
  - zlib=1.2.13
  - pip:
    - -e .
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - attrs==22.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - blosc==1.11.1
    - blosc2==2.0.0
    - boto3==1.26.74
    - botocore==1.29.74
    - brotli==1.0.9
    - cachetools==5.3.0
    - caveclient==5.0.1
    - cffi==1.15.1
    - chardet==5.1.0
    - charset-normalizer==3.0.1
    - click==8.1.3
    - cloud-files==4.12.0
    - cloud-volume==8.18.1
    - compressed-segmentation==2.2.0
    - compresso==3.2.0
    - contourpy==1.0.7
    - crackle-codec==0.3.0
    - crc32c==2.3.post0
    - cycler==0.11.0
    - cython==0.29.33
    - dataclasses==0.6
    - deflate==0.3.0
    - defusedxml==0.7.1
    - dill==0.3.6
    - dracopy==1.2.0
    - exceptiongroup==1.1.0
    - fastjsonschema==2.16.2
    - fastremap==1.13.4
    - fonttools==4.38.0
    - fpzip==1.2.0
    - fqdn==1.5.1
    - gevent==22.10.2
    - google-api-core==2.11.0
    - google-auth==2.16.1
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.7.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.1
    - googleapis-common-protos==1.58.0
    - greenlet==2.0.2
    - h5py==3.8.0
    - idna==3.4
    - imageio==2.25.1
    - inflection==0.5.1
    - iniconfig==2.0.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.2
    - isoduration==20.11.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-events==0.6.3
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.1
    - jupyter-server==2.3.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.2
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - lxml==4.9.2
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - meshparty==1.16.9
    - mistune==2.0.5
    - msgpack==1.0.4
    - multiprocess==0.70.14
    - multiwrapper==0.1.1
    - nbclassic==0.5.2
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - networkx==3.0
    - nglui==2.12.1
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.56.4
    - numexpr==2.8.4
    - numpy==1.23.5
    - orjson==3.8.6
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - pathos==0.3.0
    - patsy==0.5.3
    - pcg-skel==0.3.1
    - pillow==9.4.0
    - pluggy==1.0.0
    - plyfile==0.7.4
    - pooch==1.6.0
    - posix-ipc==1.1.1
    - pox==0.3.2
    - ppft==1.7.6.6
    - prometheus-client==0.16.0
    - protobuf==4.22.0
    - py-cpuinfo==9.0.0
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.3
    - pycparser==2.21
    - pymeshfix==0.16.2
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pysimdjson==5.0.2
    - pyspng-seunglab==1.0.0
    - pytest==7.2.1
    - python-json-logger==2.0.7
    - python-jsonschema-objects==0.4.1
    - pytz==2022.7.1
    - pyvista==0.38.2
    - pyyaml==6.0
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - rtree==1.0.1
    - s3transfer==0.6.0
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - scooby==0.7.1
    - seaborn==0.12.2
    - send2trash==1.8.0
    - shapely==2.0.1
    - simplejpeg==1.6.5
    - sniffio==1.3.0
    - soupsieve==2.4
    - sqlitedict==2.1.0
    - standard-transform==1.0.0
    - statsmodels==0.13.5
    - tables==3.8.0
    - tenacity==8.2.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tqdm==4.64.1
    - trimesh==3.20.0
    - uri-template==1.2.0
    - urllib3==1.26.14
    - vtk==9.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==3.6.2
    - xarray==2023.2.0
    - zfpc==0.1.2
    - zfpy==1.0.0.post3
    - zope-event==4.6
    - zope-interface==5.5.2
    - zstandard==0.19.0
prefix: /opt/anaconda3/envs/allen_v1dd
